/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89,?
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.

Sample Input
2
10
100

Sample Output
10
44

*/

#include <cmath>
#include <cstdio>
#include <vector>
#include <iostream>
#include <algorithm>
#include<math.h>

using namespace std;
int main() {
    system("cls");
    long unsigned int sum1[10000],n,f,s,t=0,sum,k=0,j=0,i=0,sum2,t1;
    cin>>t;
    while(t!=0){
               fflush(stdin);
                cin>>n;
                f=0;
                s=1;
                t1=0;
                sum=0;
                sum2=0;
                for(i=0;i<n;i++){
                           t1=f+s;
                           if(t1%2==0&&t1<n){
                                             sum=sum+t1; 
                                   }
                           else{
                                sum2=sum2+t1;
                                }
                           f=s;
                           s=t1;
                           }
                sum1[k]=sum;k++;
                t--;
                }
    j=0;
    while(j<k){
               cout<<sum1[j]<<endl;
               j++;
               }
    system("pause");
    return 0;
}
